name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: do the shits
      run: |
        cd binary
        curl https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -O -J -L   
        7z x premake-5.0.0-beta2-windows.zip
        dir
        git clone https://github.com/keganpowers34/garrysmod_common.git --recursive -b x86-64-support-sourcesdk
        git clone https://github.com/NVIDIAGameWorks/FleX.git
        git clone https://github.com/Derpius/BSPParser.git
        git clone https://github.com/Derpius/GMFS.git
        ./premake5.exe vs2022
        
    - name: Add msbuild to PATH 
      uses: microsoft/setup-msbuild@v2
      with: 
          msbuild-architecture: 'x64'
          
    - name: Build app for release
      run: msbuild D:\a\gwater2\gwater2\binary\gmcl_gwater2.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -p:platform=x64
      
    - name: check if the shits is there or its not
      run: |
        cd D:\a\gwater2\gwater2\binary\
        dir    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: gmcl_gwater2_win64.dll
          path: D:\a\gwater2\gwater2\binary\x86_64\Release\gmcl_gwater2_win64.dll
          if-no-files-found: error
    
