name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: do the shits
      run: |
        cd binary
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz          
        tar -xf premake-5.0.0-beta2-linux.tar.gz
        git clone https://github.com/danielga/garrysmod_common.git --recursive -b x86-64-support-sourcesdk
        ./premake5 vs2022
        ls -r
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
