name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: do the shits
      run: |
        dir
        cd ..
        dir
        cd ..
        dir
        cd ..
        dir
        cd binary
        curl https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -O -J -L   
        7z x premake-5.0.0-beta2-windows.zip
        dir
        git clone https://github.com/danielga/garrysmod_common.git --recursive -b x86-64-support-sourcesdk
        ./premake5.exe vs2022
    - name: Compile Visual Studio project with MSBuild
      shell: cmd 
      run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild' }}
      working-directory: path/to/your/project
