name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: do the shits
      run: |
        cd binary
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz          
        tar -xf premake-5.0.0-beta2-linux.tar.gz
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install libz1 libncurses5 libbz2-1.0:i386 libstdc++6 libbz2-1.0 gcc-multilib g++-multilib
        git clone https://github.com/danielga/garrysmod_common.git --branch x86-64-support-sourcesdk --recursive
        ./premake5 gmake
        ls -r
        make check
