name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download premake
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz          
    - name: pull it out
      run: tar -xf premake-5.0.0-beta2-linux.tar.gz
    - name: premake
      run: | 
        ./premake5 gmake
    - name: wtf
    - run: |
        ls -r
